version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: MarkdownSnippets.MsBuild
    versions:
    - 22.0.3
    - 23.0.1
    - 23.0.2
    - 23.1.0
    - 23.1.1
  - dependency-name: ApprovalTests
    versions:
    - 5.4.5
    - 5.4.6
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
